name: Chroma
description: The AI-native open-source embedding database
instructions: null
changeLog:
  - date: 2023-07-18
    description: First Release
links:
  - label: Website
    url: https://trychroma.com/
  - label: Documentation
    url: https://docs.trychroma.com/
  - label: Github
    url: https://github.com/chroma-core/chroma
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: chroma
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/chroma-core/chroma:latest
