name: Botpress
description: Dev tools to reliably understand text and automate conversations. Built-in NLU. Connect & deploy on any messaging channel (Slack, MS Teams, website, Telegram, etc).
instructions: Botpress needs at least 10 GB of RAM to run!
changeLog:
  - date: 2023-5-18
    description: first release
links:
  - label: Website
    url: https://botpress.com
  - label: Documentation
    url: https://botpress.com/docs
  - label: Github
    url: https://github.com/botpress/botpress
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - redisServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: botpress
    appServiceImage:
      type: string
      title: App Service Image
      default: botpress/server:latest
    databaseServiceName:
      type: string
      title: Database Service Name
      default: botpress-db
    redisServiceName:
      type: string
      title: Redis Service Name
      default: redis-db
